version: '3.7'

services:
 postgres:
    image: "postgres:9.6.1"
    ports:
      - "5432:5432"
 app:
    image: "node:alpine"
    restart: always
    env_file: .env
    build: 
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - NODE_ENV=production
    ports:
      - "8080:8080"
    depends_on:
      - postgres