version: '3.7'

services:
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
  app:
    container_name: app
    external_links:
      - mongo
    depends_on:
      - mongo